# Generated by Django 2.2.5 on 2019-09-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_table_takeorderform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakeOrderForm',
        ),
    ]
