# Generated by Django 2.2.5 on 2019-09-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_table_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Table'),
        ),
    ]
