# Generated by Django 2.2.5 on 2019-09-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190910_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('number', models.IntegerField(null=True)),
                ('bill_type', models.CharField(max_length=100, null=True)),
                ('user_str', models.CharField(max_length=100, null=True)),
                ('sub_total', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('service_charge_percent', models.FloatField(default=0)),
                ('service_charge_amount', models.FloatField(default=0)),
                ('taxable_amount', models.FloatField(default=0)),
                ('vat_percent', models.FloatField(default=0)),
                ('vat_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('active', models.IntegerField(default=1)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Customer')),
                ('Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Table')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Bill'),
        ),
    ]
