# Generated by Django 2.2.5 on 2019-09-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190911_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='number',
            new_name='billno',
        ),
        migrations.AddField(
            model_name='bill',
            name='pan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
